### ISSUE TITLE
No module named 'wx' error when running after installation

### ISSUE THREAD

**Issue by Jellybit** [FlorianEagox/weeablind#14]
After following the instructions on windows, I try to run weeblind.py, but get the following error:

Traceback (most recent call last):
  File "D:\Weeablind\weeablind.py", line 1, in <module>
    import wx
ModuleNotFoundError: No module named 'wx'

After installing wxpython, it gets a bit further, only to give this error:

Traceback (most recent call last):
  File "D:\Weeablind\weeablind.py", line 3, in <module>
    from tabs.ConfigureVoiceTab import ConfigureVoiceTab
  File "D:\Weeablind\tabs\ConfigureVoiceTab.py", line 2, in <module>
    import app_state
  File "D:\Weeablind\app_state.py", line 1, in <module>
    from Voice import Voice
  File "D:\Weeablind\Voice.py", line 5, in <module>
    import feature_support
  File "D:\Weeablind\feature_support.py", line 10, in <module>
    diarization_supported = is_module_available("pyannote.audio")
  File "D:\Weeablind\feature_support.py", line 6, in is_module_available
    return importlib.util.find_spec(module_name) is not None
  File "C:\Users\winuser\anaconda3\envs\wee\lib\importlib\util.py", line 94, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ModuleNotFoundError: No module named 'pyannote'

**Comment by FlorianEagox** [comment]
Oop, I will fix this, it should have been installed with the requirements as pip install pyannote.audio, but maybe it wasn't for some reason. The feature support should also check to make sure that's installed before trying to import it. WIll fix that soon
