### ISSUE TITLE
Issue with "julius" Module Not Found Error

### ISSUE THREAD

**Issue by fralapo** [FlorianEagox/weeablind#18]
I ran into a snag while using your project and wanted to reach out about it. Seems like there's an issue with the "julius" module not being found, even though I've installed all the dependencies correctly.

Here's the error I'm getting:
`Traceback (most recent call last):
  File "C:\WINDOWS\system32\weeablind\weeablind.py", line 4, in <module>
    from tabs.SubtitlesTab import SubtitlesTab
  ...
  File "C:\Windows\System32\weeablind\venv\Lib\site-packages\torch_audiomentations\augmentations\band_pass_filter.py", line 1, in <module>
    import julius
ModuleNotFoundError: No module named 'julius'`

I double-checked everything in my virtual environment, and it all seems in order. Any ideas on how I can fix this? Any additional steps or configurations I might be missing?

Thanks a bunch for your help!

**Comment by fralapo** [comment]
solved with `pip download julius` and inside the folder where it downloaded `pip install julius-0.2.7.tar.gz`
